### ISSUE TITLE
Add timestamp fields

### ISSUE THREAD

**Issue by nickolasrm** [CITEI/EducaZika#11]
There are some models that are useful to keep track of when an action was performed or created. These timestamps are useful because the researches will be able to interpret the gaps and the relation within the data without making us to implement a difficult incremental link between the data rows. The fields that must be added are described below:

* `User -> Progress -> History -> [Box] -> CompletedAt`: Whenever a user completes a box, the server is going to move this box and its answers to the history field. When this action is performed, make sure to add a new timestamp field. This will transform the history a time series data
* `User -> CreatedAt`: When the user registers in the DB, the app currently doesn't saves its registration date. This would be useful to have because the researchers can cross this data with the `CompletedAt` to see if the users are stuck in a specific stage. Whenever a register action is performed, add the CreatedAt field with the current timestamp. This can be automatically added using mongoose

**Comment by davi-o-barbosa** [comment]
#50 Executou essa tarefa.
