### ISSUE TITLE
Edit operation failing

### ISSUE THREAD

**Issue by nickolasrm** [CITEI/EducaZika#15]
Validate if the edit operations are working properly. I know updating files is a great problem when it comes to editting, and it might be pain in the ass to recreate the fields instead of editing them.

Find what edit operations are not working, and estimate the cost of fixing it. If fixing it is too expensive, just remove the edit operation for a model

**Comment by nickolasrm** [comment]
Se o deadline estiver apertado, remova as operações de edição para as collections que falham. Geralmente isso é por conta da função de upload na activity

**Comment by nickolasrm** [comment]
@deiveria me lembro de você ter editado esse cara aqui. Pode colocar os comentários do que fez na issue?

**Comment by davi-o-barbosa** [comment]
Eu não fiz nada em específico, atualizar o adminJS resolveu os problemas aparentemente
