### ISSUE TITLE
Swagger

### ISSUE THREAD

**Issue by nickolasrm** [CITEI/EducaZika#21]
Because the server API contains lots of routes and different ways to perform requests, it is a good practice to have a /swagger route for documenting the API payload, parameters and routes. Study about integrating swagger with express, and implement a documentation for the game routes (not the admin panel).

**Comment by paulawritesit** [comment]
Hello, I'm interested in contributing to open-source documentation. Can I help with this issue?

**Comment by nickolasrm** [comment]
Hey @paulawritesit I'm really happy you want to help us developing this project! We've opened the source code in order to leave the community to contribute and to benefit from it. However, @deiveria is already going to work in this topic, so I thought you could review his PR. Does that work for you?

**Comment by paulawritesit** [comment]
Yes, that's great; I look forward to seeing their work!

**Comment by davi-o-barbosa** [comment]
#49 terminou essa tarefa.
