### ISSUE TITLE
Fix AdminJS panel to users.

### ISSUE THREAD

**Issue by davi-o-barbosa** [CITEI/EducaZika#33]
When trying to access the users list in the panel it gives this error:
```'Invalid regular expression: /^progress(\\.|\\.\\d+\\.)box(\\.|\\.\\d+\\.)$*(\\.|\\.\\d+\\.)module($|\\.)/: Nothing to repeat'```

It seems related to both fields with `'ref'` inside Box schema, at `user.progress.box`. 
If you remove both **module** and **activities** fields from **Box** it works again. 
It is related to the changes I made at the commit https://github.com/CITEI/Comunizika/commit/368ed3f45a9eb94cb61307654d22f42d0f2477fe because it was working before (at https://github.com/CITEI/Comunizika/commit/0fd70a55bc6d60713f600940c2bb4ee0c523e013).

After this is fixed all files related to Stage can finally be removed.

**Comment by nickolasrm** [comment]
Relacionada ao #17 e ao #37
