### ISSUE TITLE
Diagramação da nova API

### ISSUE THREAD

**Issue by nickolasrm** [CITEI/EducaZika#35]
## Descrição

Com as mudanças estruturais pedidas pela banca na aplicação é necessário que antes do desenvolvimento seja construido um diagrama de sequência bem como o planejamento dos payloads envolvidos na nova lógica do bakend.

**Essa task é necessária pois permite ao frontend trabalhar sem a necessidade do backend estar pronto.**

Algumas ferramentas que podem ajudar nesse trabalho:
- [plantuml](https://plantuml.com/sequence-diagram)
- [mermaid](https://mermaid.js.org/syntax/sequenceDiagram.html) (Recomendo utilizar esse pois o Github tem compatibilidade nativa com mermaid)
- [diagrams.net](https://www.diagrams.net/)

### Diagrama de login:

```mermaid
sequenceDiagram
    User->>App: Efetua login
    App->>API: Envia credenciais
    API->>DB: Puxa user do banco
    DB-->>API: Credenciais
    API->>API: Validar
    alt valido
        API-->>App: Token
        App-->>User: Dashboard
    else invalido
        API-->>App: 403
        App-->>User: Mensagem de erro
    end
```

### Payload:

```typescript
interface Auth {
    email: string,
    password: string
}
```

## Criterio de sucesso

- Entendimento do fluxo e validação pelo @cesarzxk 
- Diagramas e payloads das rotas desde o cadastro até o fim do jogo

**Comment by davi-o-barbosa** [comment]
https://github.com/CITEI/Comunizika/pull/46
