### ISSUE TITLE
Bug: Criar módulo

### ISSUE THREAD

**Issue by davi-o-barbosa** [CITEI/EducaZika#47]
Ao criar um novo módulo pelo painel de administrador ele causa um erro caso nenhuma atividade seja selecionada, porém isso não impede a criação ou atrapalha a funcionalidade.

**Comment by nickolasrm** [comment]
@deiveria esse problema foi corrigido, me lembro que você falou uma solução no disco

**Comment by davi-o-barbosa** [comment]
Resolvido após investigação
